# Generated by Django 5.1.4 on 2025-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_specialization_booking_review_specialistprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="consultation_type",
            field=models.CharField(
                choices=[("VIDEO", "Video Call"), ("VISIT", "Farm Visit")],
                default="VIDEO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="video_room_sid",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
