# Generated by Django 5.1.4 on 2025-01-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_booking_consultation_type_booking_video_room_sid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
