# Generated by Django 5.1.4 on 2025-01-03 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_payment_expiry_date_payment_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cropanalysis",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="cropanalysis",
            name="detected_disease",
        ),
        migrations.RemoveField(
            model_name="cropanalysis",
            name="image_url",
        ),
        migrations.AddField(
            model_name="cropanalysis",
            name="image",
            field=models.ImageField(default=1, upload_to="crop_images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cropanalysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cropanalysis",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cropanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cropanalysis",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
