# Generated by Django 4.2.9 on 2025-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="UGX", editable=False, max_length=3),
        ),
    ]
