# Generated by Django 4.2.9 on 2025-01-03 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("tractor", "Tractor"),
                            ("harvester", "Harvester"),
                            ("planter", "Planter"),
                            ("irrigation", "Irrigation System"),
                            ("sprayer", "Sprayer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("specifications", models.JSONField(default=dict)),
                ("images", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialist_type",
                    models.CharField(
                        choices=[
                            ("agronomist", "Agronomist"),
                            ("veterinarian", "Veterinarian"),
                            ("soil_expert", "Soil Expert"),
                            ("pest_control", "Pest Control Expert"),
                            ("machinery_expert", "Machinery Expert"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField()),
                ("qualifications", models.JSONField()),
                ("experience_years", models.PositiveIntegerField()),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_hours", models.JSONField()),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("languages", models.JSONField(default=list)),
                ("location", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_specialist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-total_reviews"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("object_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to="marketplace.equipment",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In Person"),
                            ("video_call", "Video Call"),
                            ("voice_call", "Voice Call"),
                            ("chat", "Chat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("problem_description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="marketplace.specialist",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_time"],
            },
        ),
        migrations.AddIndex(
            model_name="specialist",
            index=models.Index(
                fields=["specialist_type"], name="marketplace_special_b0f528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specialist",
            index=models.Index(
                fields=["location"], name="marketplace_locatio_3e29a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specialist",
            index=models.Index(
                fields=["is_verified"], name="marketplace_is_veri_ed1bd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="marketplace_content_502dc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="marketplace_rating_c67539_idx"),
        ),
        migrations.AddIndex(
            model_name="rental",
            index=models.Index(fields=["status"], name="marketplace_status_257f38_idx"),
        ),
        migrations.AddIndex(
            model_name="rental",
            index=models.Index(
                fields=["payment_status"], name="marketplace_payment_c57717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rental",
            index=models.Index(
                fields=["start_date"], name="marketplace_start_d_3d6bcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_type"], name="marketplace_equipme_b8f9a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["location"], name="marketplace_locatio_7f673e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["is_available"], name="marketplace_is_avai_a16505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(fields=["status"], name="marketplace_status_a4a492_idx"),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["payment_status"], name="marketplace_payment_6b7b4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["scheduled_time"], name="marketplace_schedul_f14452_idx"
            ),
        ),
    ]
